FROM mongo:8.0

EXPOSE 27017

COPY init-mongo.sh /docker-entrypoint-initdb.d/init-mongo.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.sh

CMD ["mongod", "--bind_ip_all", "--auth", "--dbpath", "/data/db"]
