FROM redis/redis-stack:7.4.0-v8

EXPOSE 6379

CMD ["redis-server", "--dir", "/data", "--save", "60", "1", "--appendonly", "yes", "--appendfsync", "everysec", "--requirepass", "iHNu53YAPSdZVPSW", "--loglevel", "warning"]
