FROM node:25.5.0 as build

ARG NEXT_APP_SERVICES_HOST=/api

WORKDIR /app

RUN npm install -g pnpm@9.4.0

COPY ./pnpm-lock.yaml /app/pnpm-lock.yaml
COPY ./pnpm-workspace.yaml /app/pnpm-workspace.yaml

COPY ./src/frontend/main-ui/package.json /app/src/frontend/main-ui/package.json

RUN pnpm install

COPY ./src/frontend/main-ui /app/src/frontend/main-ui

WORKDIR /app/src/frontend

EXPOSE 3000
#USER node

CMD ["pnpm", "dev"]
